baseURL = 'https://bits.manfred.life/'
languageCode = 'en-us'
title = "Manfred's Life."
metaDataFormat = "yaml"
theme = 'hugo-theme-techdoc'
defaultContentLanguage = "en"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = false

[params]
    title = "Manfred's Life."
    #images = ["images/og-image.png"] # static/images
    description = "Bit by Bit."

    github_repository = "https://github.com/moul/bits.manfred.life"
    #version = "0.0.1-dev"

    github_doc_repository = "https://github.com/moul/bits.manfred.life"
    github_doc_repository_path = ""
    github_doc_repository_branch = "main"

    # analytics


    custom_font_color = ""
    custom_background_color = ""

    menu_style = "open-menu"

    dateformat = "" # 2 Jan 2006

    menu_exclusion = ["archives"]

    algolia_search_enable = false

[menu]
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    identifier = "home"
    pre = "<i class='fa fa-heart'></i>&nbsp;"

[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/moul"
    weight = 2
    identifier = 'twitter'
    [menu.main.params]
        class = 'twitter-menu-item'

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe = true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

[outputs]
    home = ["HTML", "RSS"]


[module]
[[module.imports]]
path = "github.com/thingsym/hugo-theme-techdoc"
